export const models = [
  {
    id: '12k-110v',
    name: '12,000 BTU',
    voltage: '110V',
    voltageType: 'blue',
    seer: 21.0,
    area: '12-15',
    recommended: 'Habitaciones y oficinas pequeñas',
    features: {
      noise: '40.5/35.5/33 dB',
      current: '8.5A',
      energyRating: 'A+++',
    },
    highlight: 'Ideal para hogares',
    certificate: 'Certificado AHRI 12KBTU 110V-SEER2 21-Serie WX.pdf',
  },
  {
    id: '12k-220v',
    name: '12,000 BTU',
    voltage: '220V',
    voltageType: 'purple',
    seer: 21.5,
    area: '12-15',
    recommended: 'Espacios residenciales medianos',
    features: {
      noise: '40.5/36.0/26.5 dB',
      current: '7.0A',
      energyRating: 'A+++',
    },
    highlight: 'Máxima eficiencia',
    certificate: 'Certificado AHRI 12KBTU-SEER2 21.5-Serie WX.pdf',
  },
  {
    id: '18k-220v',
    name: '18,000 BTU',
    voltage: '220V',
    voltageType: 'purple',
    seer: 21.0,
    area: '16-23',
    recommended: 'Salas y espacios abiertos',
    features: {
      noise: '46/38.5/31.5 dB',
      current: '6.8A',
      energyRating: 'A++',
    },
    highlight: 'Balance perfecto',
    certificate: 'Certificado AHRI 18KBTU-SEER2 21-Serie WX.pdf',
  },
  {
    id: '24k-220v',
    name: '24,000 BTU',
    voltage: '220V',
    voltageType: 'purple',
    seer: 20.0,
    area: '24-30',
    recommended: 'Oficinas y locales comerciales',
    features: {
      noise: '47.5/39.5/36 dB',
      current: '9.3A',
      energyRating: 'A++',
    },
    highlight: 'Alto rendimiento',
    certificate: 'Certificado AHRI 24KBTU-SEER2 20-Serie WX.pdf',
  },
  {
    id: '36k-220v',
    name: '36,000 BTU',
    voltage: '220V',
    voltageType: 'purple',
    seer: 18.0,
    area: '30-45',
    recommended: 'Grandes espacios comerciales',
    features: {
      noise: '54/45/40 dB',
      current: '16.8A',
      energyRating: 'A+',
    },
    highlight: 'Máxima potencia',
    certificate: 'Certificado AHRI 36KBTU-SEER2 18-Serie WX.pdf',
  },
];

export const mainFeatures = [
  {
    icon: '❄️',
    title: 'Tecnología Inverter',
    description: 'Control preciso de temperatura',
    color: 'blue',
  },
  {
    icon: '🌱',
    title: 'Eco-friendly',
    description: 'Refrigerante R410A',
    color: 'green',
  },
  {
    icon: '📱',
    title: 'WiFi Opcional',
    description: 'Control desde tu smartphone',
    color: 'purple',
  },
  {
    icon: '🔋',
    title: 'Alta Eficiencia',
    description: 'Clasificación SEER superior',
    color: 'yellow',
  },
];
